/*
 * LoadEventTypesPanel.java
 *
 * Created on August 27, 2006, 2:57 PM
 */

package edu.iisc.tdminer.gui.simulator;

import edu.iisc.tdminer.util.Constants;
import java.awt.Component;
import java.awt.Container;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.NumberFormat;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  Deb
 */
public class LoadEventTypesPanel extends javax.swing.JPanel
{
    private JDialog dialog;
    private StringBuffer buffer = new StringBuffer();
    
    /** Creates new form LoadEventTypesPanel */
    public LoadEventTypesPanel(JDialog dialog)
    {
        this.dialog = dialog;
        initComponents();
        setEnable(false, jPanelLoad);
    }
    
    public String getEventTypes()
    {
        if (buffer != null)
            return buffer.toString();
        
        return null;
    }
    
    private void add(String t)
    {
        buffer.append(t);
        buffer.append(" ");
    }
    
    private void setEnable(boolean enable, Component c)
    {
        c.setEnabled(enable);
        if (c instanceof Container)
        {
            Container cont = (Container)c;
            int count = cont.getComponentCount();
            if (count > 0)
            {
                for(int i = 0; i < count; i++)
                {
                    Component child = cont.getComponent(i);
                    setEnable(enable, child);
                }
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonGenerate = new javax.swing.JRadioButton();
        jRadioButtonLoad = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelGenerate = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrefix = new javax.swing.JTextField();
        jPanelLoad = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFileName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Method for generating/loading event types")));
        buttonGroup1.add(jRadioButtonGenerate);
        jRadioButtonGenerate.setSelected(true);
        jRadioButtonGenerate.setText("Generate event types");
        jRadioButtonGenerate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonGenerate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonGenerate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonGenerateActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButtonGenerate);

        buttonGroup1.add(jRadioButtonLoad);
        jRadioButtonLoad.setText("Load event types from file");
        jRadioButtonLoad.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonLoad.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonLoad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonLoadActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButtonLoad);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jPanelGenerate.setLayout(new java.awt.GridLayout(2, 2, 10, 5));

        jPanelGenerate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Generate event types")));
        jLabel3.setText("Number of event types");
        jPanelGenerate.add(jLabel3);

        jTextFieldCount.setText("50");
        jPanelGenerate.add(jTextFieldCount);

        jLabel4.setText("Event type prefix");
        jPanelGenerate.add(jLabel4);

        jTextFieldPrefix.setText("E");
        jPanelGenerate.add(jTextFieldPrefix);

        jPanel2.add(jPanelGenerate);

        jPanelLoad.setLayout(new java.awt.BorderLayout(10, 10));

        jPanelLoad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Load event types from file")));
        jLabel5.setText("File:");
        jPanelLoad.add(jLabel5, java.awt.BorderLayout.WEST);

        jPanelLoad.add(jTextFieldFileName, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Open16.gif")));
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jPanelLoad.add(jButton1, java.awt.BorderLayout.EAST);

        jLabel6.setText("Select file containing event types");
        jPanelLoad.add(jLabel6, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanelLoad);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 5, 5));

        jPanel3.add(jLabel1);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonCancel);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonOkActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonOk);

        jPanel3.add(jLabel2);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
// TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
	if (Constants.CURRENT_DIR != null) fc.setCurrentDirectory(Constants.CURRENT_DIR);
        fc.showOpenDialog(dialog);
	Constants.CURRENT_DIR = fc.getCurrentDirectory();
        
        File path = fc.getSelectedFile();
        jTextFieldFileName.setText(path.getAbsolutePath());      
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOkActionPerformed
    {//GEN-HEADEREND:event_jButtonOkActionPerformed
// TODO add your handling code here:
        boolean success = true;
        if (jRadioButtonGenerate.isSelected())
        {
            try
            {
                int count = Integer.parseInt(jTextFieldCount.getText());
                String prefix = jTextFieldPrefix.getText().trim();
                if (prefix.indexOf(' ') != -1)
                {
                    JOptionPane.showMessageDialog(this, "Event type prefix cannot contain spaces", "Error reading event type prefix", JOptionPane.ERROR_MESSAGE);
                    success = false;
                }
                else
                {
                    String s = Integer.toString(count - 1);
                    int l = s.length();
                    NumberFormat nf = NumberFormat.getInstance();
                    nf.setMinimumIntegerDigits(l);
                    nf.setGroupingUsed(false);
                    for (int i = 0; i < count; i++)
                    {
                        add(prefix + nf.format(i));
                    }
                }
            }
            catch (NumberFormatException nfe)
            {
                JOptionPane.showMessageDialog(this, nfe.getMessage(), "Error reading number of event types", JOptionPane.ERROR_MESSAGE);
                success = false;
            }
        }
        else if (jRadioButtonLoad.isSelected())
        {
            File file = new File(jTextFieldFileName.getText());
            if (file.exists())
            {
                try
                {
                    BufferedReader in = new BufferedReader(new FileReader(file));
                    String line = null;
                    while((line = in.readLine()) != null)
                    {
                        line = line.trim();
                        if (line.indexOf(' ') != -1)
                        {
                            JOptionPane.showMessageDialog(this, "Space is not allowed in event types: " + line, "Error reading event types from file", JOptionPane.ERROR_MESSAGE);
                            success = false;
                            break;
                        }
                        else
                        {
                            add(line);
                        }
                    }
                    in.close();
                }
                catch (IOException ioe)
                {
                    JOptionPane.showMessageDialog(this, ioe.getMessage(), "Error reading event types from file", JOptionPane.ERROR_MESSAGE);
                    success = false;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "File " + file.getAbsolutePath() + " not found.", "Error reading event types from file", JOptionPane.ERROR_MESSAGE);
                success = false;
            }
        }
        
        if (success)
        {
            dialog.setVisible(false);
            dialog.dispose();
        }
    }//GEN-LAST:event_jButtonOkActionPerformed
    
    private void jRadioButtonLoadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonLoadActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonLoadActionPerformed
// TODO add your handling code here:
        if (jRadioButtonLoad.isSelected())
        {
            setEnable(true, jPanelLoad);
            setEnable(false, jPanelGenerate);
        }
    }//GEN-LAST:event_jRadioButtonLoadActionPerformed
    
    private void jRadioButtonGenerateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonGenerateActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonGenerateActionPerformed
// TODO add your handling code here:
        if (jRadioButtonGenerate.isSelected())
        {
            setEnable(true, jPanelGenerate);
            setEnable(false, jPanelLoad);
        }
    }//GEN-LAST:event_jRadioButtonGenerateActionPerformed
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
// TODO add your handling code here:
        buffer = null;
        dialog.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelGenerate;
    private javax.swing.JPanel jPanelLoad;
    private javax.swing.JRadioButton jRadioButtonGenerate;
    private javax.swing.JRadioButton jRadioButtonLoad;
    private javax.swing.JTextField jTextFieldCount;
    private javax.swing.JTextField jTextFieldFileName;
    private javax.swing.JTextField jTextFieldPrefix;
    // End of variables declaration//GEN-END:variables
    
}
