/*
 * PoissonSynapticDelayDialog.java
 *
 * Created on February 22, 2007, 12:04 PM
 */

package edu.iisc.tdminer.gui.simulator;

import java.awt.Frame;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeListener;

/**
 *
 * @author  Debprakash Patnaik
 */
public class PoissonSynapticDelayDialog extends javax.swing.JDialog
{
    private boolean success = false;
    
    /** Creates new form PoissonSynapticDelayDialog */
    public PoissonSynapticDelayDialog(Frame frame, boolean modal, int index)
    {
        super(frame, modal);
        initComponents();
        jSpinnerSynapticDelay.setModel(new SpinnerNumberModel(index, 1, 100, 1));
        setSize(250,100);
        if (frame != null)
        {
            int x = (int)(frame.getLocation().getX() + (frame.getSize().getWidth() - getSize().getWidth())/2);
            int y = (int)(frame.getLocation().getY() + (frame.getSize().getHeight() - getSize().getHeight())/2);
            setLocation(x,y);
        }
    }
    
    public static int getSynapticDelay(String title, int index, Frame parent)
    {
        PoissonSynapticDelayDialog d = new PoissonSynapticDelayDialog(parent, true, index);
        d.setTitle(title);
        d.setVisible(true);
        if (d.success)
        {
            System.out.println("Current Index = " + d.jSpinnerSynapticDelay.getValue());
            return ((Integer)d.jSpinnerSynapticDelay.getValue()).intValue();
        }
        return -1;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerSynapticDelay = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.BorderLayout(10, 0));
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.BorderLayout(15, 15));
        
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel1.setText("<html>T<sub>synapse</sub> = </html>");
        jLabel1.setToolTipText("(Synaptic delay)");
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);
        
        jSpinnerSynapticDelay.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel1.add(jSpinnerSynapticDelay, java.awt.BorderLayout.CENTER);
        
        jLabel2.setText("<html>x T<sub>update</sub> sec</html>");
        jPanel1.add(jLabel2, java.awt.BorderLayout.EAST);
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        
        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonOkActionPerformed(evt);
            }
        });
        
        jPanel2.add(jButtonOk);
        
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });
        
        jPanel2.add(jButtonCancel);
        
        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        success = false;
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOkActionPerformed
    {//GEN-HEADEREND:event_jButtonOkActionPerformed
        success = true;
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed
    
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerSynapticDelay;
// End of variables declaration//GEN-END:variables
    
}
