/*
 * AddEpisodePanel.java
 *
 * Created on August 28, 2006, 12:53 AM
 */

package edu.iisc.tdminer.gui;

import edu.iisc.tdminercore.data.ComboEpisode;
import edu.iisc.tdminercore.data.EventFactor;
import edu.iisc.tdminercore.data.IEpisode;
import edu.iisc.tdminercore.data.Episode;

import edu.iisc.tdminercore.data.Interval;
import edu.iisc.tdminercore.util.SerialEpisodeParser;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.prefs.Preferences;
import javax.swing.JDialog;

/**
 *
 * @author  Deb
 */
public class AddEpisodePanel extends javax.swing.JPanel
{
    private final static Preferences prefs = Preferences.userNodeForPackage( AddEpisodePanel.class );
    
    private EventFactor eventTypes;
    private List<Interval> ivlList;
    private boolean cancelled = true;
    private JDialog dialog;
    
    public enum CallMode {
        SIMULATOR, COUNTING_WITH_INTERVALS, COUNTING_OTHERS
    };
    private CallMode callerType;
    
    /** Creates new form AddEpisodePanel */
    
    public static List<IEpisode> getEpisode(EventFactor eventTypes, Frame frame, CallMode callerType, List<Interval> ivlList) 
        throws Exception
    {
        JDialog dialog = new JDialog(frame,"Event types selection", true);
        dialog.setSize(360,300);
        
        if (frame != null)
        {
            int x = (int)(frame.getLocation().getX() + (frame.getSize().getWidth() - dialog.getSize().getWidth())/2);
            int y = (int)(frame.getLocation().getY() + (frame.getSize().getHeight() - dialog.getSize().getHeight())/2);
            dialog.setLocation(x,y);
        }
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        AddEpisodePanel panel = new AddEpisodePanel(eventTypes, dialog, callerType, ivlList);
        dialog.getContentPane().add(panel);
        dialog.setVisible(true);
        return panel.getEpisode();
    }
    
    private AddEpisodePanel(EventFactor eventTypes, JDialog dialog, CallMode callerType, List<Interval> ivlList)
    {
        this.eventTypes = eventTypes;
        this.dialog = dialog;
        this.ivlList = ivlList;
        initComponents();    
        
        switch(callerType)
        {
            case COUNTING_OTHERS:
                jTextAreaEpisodes.setText( prefs.get("episodeSet-COUNTING-OTHERS","") );
                break;
            case COUNTING_WITH_INTERVALS:
                jTextAreaEpisodes.setText( prefs.get("episodeSet-COUNTING-WITH-INTERVALS","") );
                break;
            case SIMULATOR:
                jTextAreaEpisodes.setText( prefs.get("episodeSet-SIMULATOR","") );
                break;
        }
        this.callerType = callerType;
    }
    
    
    private List<IEpisode> getEpisode() throws Exception
    {
        List<IEpisode> eList = new ArrayList<IEpisode>();
        String[] lines = jTextAreaEpisodes.getText().split("\n");
        
        if (cancelled) return null;
        if (lines.length < 1) return null;
        
        for(String line : lines) {
            if (line.trim().length() < 1) continue;
            switch (this.callerType) {
                case COUNTING_OTHERS:
                    eList.add( Episode.getEpisode(line.trim(), eventTypes, ivlList) );
                    break;
                case COUNTING_WITH_INTERVALS:
                    if (SerialEpisodeParser.hasSerialEpisode(line))
                    {
                      System.out.println("Serial Episode with inter-event times found!!!");
                      eList.add(SerialEpisodeParser.getSerialEpisode(line, eventTypes, ivlList));
                    }
                    break;
                case SIMULATOR:
                    eList.add( ComboEpisode.getEpisode(line.trim(), eventTypes) );
                    break;
            }
        }
        return eList;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jPanelBatch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEpisodes = new javax.swing.JTextArea();
        jPanelAction = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jComboBoxEventTypes = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel1.setText("Please enter episodes ( E.g. A B C D E)  one per line");

        jPanelBatch.setLayout(new java.awt.BorderLayout());

        jPanelBatch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextAreaEpisodes.setColumns(20);
        jTextAreaEpisodes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEpisodes);

        jPanelBatch.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanelAction.add(jButtonCancel);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jPanelAction.add(jButtonOk);

        jComboBoxEventTypes = new javax.swing.JComboBox(this.eventTypes.asVector());
        jComboBoxEventTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEventTypesActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jComboBoxEventTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelAction, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanelBatch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboBoxEventTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelAction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelBatch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function is called when an event type is picked from the combo box.
     * It may be possible to pre-select a position in the text area and have
     * the event type inserted at that position using '.insert' or 
     * 'replaceSelection'.
     */
    private void jComboBoxEventTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEventTypesActionPerformed
        jTextAreaEpisodes.replaceSelection(" " + jComboBoxEventTypes.getSelectedItem());
    }//GEN-LAST:event_jComboBoxEventTypesActionPerformed

    
    /**
     * Save the episode list in preferences
     */
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOkActionPerformed
    {//GEN-HEADEREND:event_jButtonOkActionPerformed
        try
        {
            switch(callerType)
            {
                case COUNTING_OTHERS:
                    prefs.put("episodeSet-COUNTING-OTHERS", jTextAreaEpisodes.getText());
                    break;
                case COUNTING_WITH_INTERVALS:
                    prefs.put("episodeSet-COUNTING-WITH-INTERVALS", jTextAreaEpisodes.getText());
                    break;
                case SIMULATOR:
                    prefs.put("episodeSet-SIMULATOR", jTextAreaEpisodes.getText());
                    break;
            }
        }catch(RuntimeException re)
        {
            re.printStackTrace();
        }

        cancelled = false;
        dialog.setVisible(false);
        dialog.dispose();        
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        cancelled = true;
        dialog.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxEventTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelBatch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEpisodes;
    // End of variables declaration//GEN-END:variables
    
}
