/*
 * EpisodeCountRangeDialog.java
 *
 * Created on January 9, 2007, 10:45 AM
 */

package edu.iisc.tdminer.gui;


import edu.iisc.tdminercore.data.IEventDataStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author phreed@gmail.com
 */
public class EventStreamJitterDialog extends javax.swing.JDialog
{
    private IEventDataStream eventseq;
    private java.awt.Frame parent;
    
    /** Creates new form EpisodeExportDialog */
    public EventStreamJitterDialog(java.awt.Frame frame, boolean modal, IEventDataStream eventseq)
    {
        super(frame, modal);
        this.parent = frame;
        this.eventseq = eventseq;
        initComponents();
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setSize(300,200);
        if (frame != null)
        {
            int x = (int)(frame.getLocation().getX() + (frame.getSize().getWidth() - getSize().getWidth())/2);
            int y = (int)(frame.getLocation().getY() + (frame.getSize().getHeight() - getSize().getHeight())/2);
            setLocation(x,y);
        }
    }
    
    /**
     * Collect the time frame info.
     * When there is any problem converting the fields into numbers 
     * infinity is used.
     */
    private double getTimeWidth()
    {
        double range;
        String startText = jTextFieldStartTime.getText();
        try {
            range = Double.parseDouble(startText);
        }
        catch (NumberFormatException ex) {
            System.out.println("not a real number");
            range = 0.0;
            jTextFieldStartTime.setText("0.0");
        }
        return range;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupScopeMode = new javax.swing.ButtonGroup();
        jPanelTimeFrame = new javax.swing.JPanel();
        jLabelStartTime = new javax.swing.JLabel();
        jTextFieldStartTime = new javax.swing.JTextField();
        jPanelAction = new javax.swing.JPanel();
        jButtonJitter = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export Options");
        jPanelTimeFrame.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("Select time frame bounds")));
        jLabelStartTime.setText("Time Span");

        jTextFieldStartTime.setName("Start");

        org.jdesktop.layout.GroupLayout jPanelTimeFrameLayout = new org.jdesktop.layout.GroupLayout(jPanelTimeFrame);
        jPanelTimeFrame.setLayout(jPanelTimeFrameLayout);
        jPanelTimeFrameLayout.setHorizontalGroup(
            jPanelTimeFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelTimeFrameLayout.createSequentialGroup()
                .add(jLabelStartTime)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldStartTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTimeFrameLayout.setVerticalGroup(
            jPanelTimeFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelTimeFrameLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jPanelTimeFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelStartTime)
                    .add(jTextFieldStartTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAction.setLayout(new java.awt.GridBagLayout());

        jButtonJitter.setText("Jitter");
        jButtonJitter.setToolTipText("Count the number of episode instances within the time frame");
        jButtonJitter.setMinimumSize(new java.awt.Dimension(70, 25));
        jButtonJitter.setPreferredSize(new java.awt.Dimension(70, 25));
        jButtonJitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJitterActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelAction.add(jButtonJitter, gridBagConstraints);

        jButtonClose.setText("Close");
        jButtonClose.setToolTipText("Close the dialog");
        jButtonClose.setMinimumSize(new java.awt.Dimension(70, 25));
        jButtonClose.setPreferredSize(new java.awt.Dimension(70, 25));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelAction.add(jButtonClose, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelAction, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanelTimeFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanelTimeFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelAction, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void jButtonJitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJitterActionPerformed
        try {
            this.eventseq.jitter(getTimeWidth());
            System.out.println("Jitter added sorting beginning");
            this.eventseq.sort();
            System.out.println("Sorting of jittered event stream now complete");
        }
        catch (Exception ex) {
            System.out.println("Adding jitter to input has failed: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonJitterActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupScopeMode;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonJitter;
    private javax.swing.JLabel jLabelStartTime;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelTimeFrame;
    private javax.swing.JTextField jTextFieldStartTime;
    // End of variables declaration//GEN-END:variables
    
}
