/*
 * ParamSelectionDialogPanel.java
 *
 * Created on March 28, 2006, 8:57 PM
 */

package edu.iisc.tdminer.gui;

import edu.iisc.tdminer.util.AlgoEntry;
import edu.iisc.tdminercore.miner.SessionInfo;
import java.awt.CardLayout;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author  Deb
 */
public class ParamSelectionDialogPanel extends javax.swing.JPanel
{
    private JDialog dialog;
    private int counterIndex;
    private ArrayList algos;
    private SessionInfo session;
    int[][] defaultSelection;
    
    /** Creates new form ParamSelectionDialogPanel */
    public ParamSelectionDialogPanel(JDialog dialog, SessionInfo session, int counterIndex, ArrayList algos)
    {
	initComponents();
	this.dialog = dialog;
	this.counterIndex = counterIndex;
	this.algos = algos;
        this.session = session;
        
	for (int i = 0; i < algos.size(); i++)
	{
	    jComboBoxAlgorithm.addItem(algos.get(i).toString());
	}
	jComboBoxAlgorithm.setSelectedIndex(counterIndex);

	NumberFormat nf = NumberFormat.getInstance();
	nf.setMaximumFractionDigits(8);
	
	double t = 0.0;
	t = session.getIntervalExpiry();
	jTextFieldIntervalExp.setText(nf.format(t));

	t = session.getIntervalExpiryLow();
	jTextFieldIntervalExpLow.setText(nf.format(t));

	t = session.getEpisodeExpiry();
	jTextFieldEpisodeExp.setText(nf.format(t));
	
	fitDefaultParameters();
    }
    
    public int getCounterIndex()
    {
	return counterIndex;
    }
    
public void fitDefaultParameters()
    {
        int index = jComboBoxAlgorithm.getSelectedIndex();
        Object objEntry = algos.get(index);
        if (objEntry instanceof AlgoEntry)
        {
            AlgoEntry entry = (AlgoEntry)objEntry;
            if (entry.isEpsExpiryEnable())
            {
                jTextFieldEpisodeExp.setEnabled(true);
                jLabelEpisodeExp.setEnabled(true);
            }
            else
            {
                jTextFieldEpisodeExp.setEnabled(false);
                jLabelEpisodeExp.setEnabled(false);
            }
            
            if (entry.isIvlHighEnable())
            {
                jTextFieldIntervalExp.setEnabled(true);
                jLabelIntervalExp.setEnabled(true);
            }
            else
            {
                jTextFieldIntervalExp.setEnabled(false);
                jLabelIntervalExp.setEnabled(false);
            }
            
            if (entry.isIvlLowEnable())
            {
                jLabelIntervalLow.setEnabled(true);
                jTextFieldIntervalExpLow.setEnabled(true);
            }
            else
            {
                jTextFieldIntervalExpLow.setText("0.0");
                jLabelIntervalLow.setEnabled(false);
                jTextFieldIntervalExpLow.setEnabled(false);
            }
        }
    }    
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxAlgorithm = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabelEpisodeExp = new javax.swing.JLabel();
        jTextFieldEpisodeExp = new javax.swing.JTextField();
        jLabelIntervalExp = new javax.swing.JLabel();
        jTextFieldIntervalExp = new javax.swing.JTextField();
        jLabelIntervalLow = new javax.swing.JLabel();
        jTextFieldIntervalExpLow = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(0, 5));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel14.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jPanel14.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Select algorithm"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel15.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel2.setText("Algorithm");
        jPanel15.add(jLabel2, java.awt.BorderLayout.WEST);

        jComboBoxAlgorithm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxAlgorithmActionPerformed(evt);
            }
        });

        jPanel15.add(jComboBoxAlgorithm, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel15);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabelEpisodeExp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEpisodeExp.setText("Episode expiry = ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel5.add(jLabelEpisodeExp, gridBagConstraints);

        jTextFieldEpisodeExp.setText("0.0");
        jTextFieldEpisodeExp.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        jPanel5.add(jTextFieldEpisodeExp, gridBagConstraints);

        jLabelIntervalExp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelIntervalExp.setText("Interval expiry = ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        jPanel5.add(jLabelIntervalExp, gridBagConstraints);

        jTextFieldIntervalExp.setText("0.0");
        jTextFieldIntervalExp.setMinimumSize(new java.awt.Dimension(40, 10));
        jTextFieldIntervalExp.setPreferredSize(new java.awt.Dimension(45, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel5.add(jTextFieldIntervalExp, gridBagConstraints);

        jLabelIntervalLow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIntervalLow.setText("to");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        jPanel5.add(jLabelIntervalLow, gridBagConstraints);

        jTextFieldIntervalExpLow.setText("0.0");
        jTextFieldIntervalExpLow.setMinimumSize(new java.awt.Dimension(40, 19));
        jTextFieldIntervalExpLow.setPreferredSize(new java.awt.Dimension(45, 19));
        jTextFieldIntervalExpLow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldIntervalExpLowActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel5.add(jTextFieldIntervalExpLow, gridBagConstraints);

        jPanel14.add(jPanel5);

        add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jButtonOk.setText("Ok");
        jButtonOk.setMaximumSize(new java.awt.Dimension(50, 25));
        jButtonOk.setMinimumSize(new java.awt.Dimension(50, 25));
        jButtonOk.setPreferredSize(new java.awt.Dimension(50, 25));
        jButtonOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonOk);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIntervalExpLowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldIntervalExpLowActionPerformed
    {//GEN-HEADEREND:event_jTextFieldIntervalExpLowActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntervalExpLowActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
// TODO add your handling code here:	
	try
	{
	    session.setIntervalExpiry(Double.parseDouble(jTextFieldIntervalExp.getText()));
	    session.setIntervalExpiryLow(Double.parseDouble(jTextFieldIntervalExpLow.getText()));
	    session.setEpisodeExpiry(Double.parseDouble(jTextFieldEpisodeExp.getText()));
            
            if (algos.get(jComboBoxAlgorithm.getSelectedIndex()) instanceof AlgoEntry)
            {
                this.counterIndex = jComboBoxAlgorithm.getSelectedIndex();
            }
	    dialog.setVisible(false);
	    dialog.dispose();
	}
	catch(NumberFormatException nfe)
	{
	    JOptionPane.showMessageDialog(this, "Invalid input : " + nfe.getMessage(), "Invalid Parameters", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jComboBoxAlgorithmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxAlgorithmActionPerformed
    {//GEN-HEADEREND:event_jComboBoxAlgorithmActionPerformed
// TODO add your handling code here:
	fitDefaultParameters();
    }//GEN-LAST:event_jComboBoxAlgorithmActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxAlgorithm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEpisodeExp;
    private javax.swing.JLabel jLabelIntervalExp;
    private javax.swing.JLabel jLabelIntervalLow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldEpisodeExp;
    private javax.swing.JTextField jTextFieldIntervalExp;
    private javax.swing.JTextField jTextFieldIntervalExpLow;
    // End of variables declaration//GEN-END:variables
    
}
