/*
 * PositionEventTypes.java
 *
 * Created on August 28, 2006, 12:53 AM
 */

package edu.iisc.tdminer.gui;

import edu.iisc.tdminercore.data.EventFactor;
import edu.iisc.tdminercore.data.IEpisode;

import java.awt.Frame;
import java.util.prefs.Preferences;
import javax.swing.JDialog;

/**
 *
 * @author  Deb
 */
public class PositionEventTypes extends javax.swing.JPanel
{
    private final static Preferences prefs = Preferences.userNodeForPackage( PositionEventTypes.class );
    
    private IEpisode episode;
    private EventFactor eventTypes;
    private boolean cancelled = false;
    private JDialog dialog;
    
    /**
     * Creates new form PositionEventTypes
     */
    
    public static void setPositions(EventFactor eventTypes, Frame frame) 
        throws Exception
    {
        JDialog dialog = new JDialog(frame,"Event types selection", true);
        dialog.setSize(360,500);
        
        if (frame != null)
        {
            int x = (int)(frame.getLocation().getX() + (frame.getSize().getWidth() - dialog.getSize().getWidth())/2);
            int y = (int)(frame.getLocation().getY() + (frame.getSize().getHeight() - dialog.getSize().getHeight())/2);
            dialog.setLocation(x,y);
        }
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        
        PositionEventTypes panel = new PositionEventTypes(eventTypes, dialog);
        dialog.getContentPane().add(panel);
        dialog.setVisible(true);
        
        return;
    }
    
    private PositionEventTypes(EventFactor eventTypes, JDialog dialog)
    {
        this.eventTypes = eventTypes;
        this.dialog = dialog;
        initComponents();    
        
        jTextAreaEpisodes.setText( prefs.get("eventPositions","") );
    }
    
    
    private void update()
    {
        String positions = jTextAreaEpisodes.getText();
        String[] lines = positions.split("\n");
        if (lines.length < 1) {
            cancelled = false;
            dialog.setVisible(false);
            dialog.dispose();
            return;
        }
       
        for( String line : lines ) {
            if (line.trim().length() < 1) continue;
            try {
                this.eventTypes.setPosition(line.trim());
            } catch (EventFactor.PositionError ex) {
                System.err.println("Invalid position request: " + line);
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jPanelBatch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEpisodes = new javax.swing.JTextArea();
        jPanelAction = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jComboBoxEventTypes = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel1.setText("Supply event type postions <name> <x> <y>, e.g.  Dog 12.5 4.5");

        jPanelBatch.setLayout(new java.awt.BorderLayout());

        jPanelBatch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextAreaEpisodes.setColumns(20);
        jTextAreaEpisodes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEpisodes);

        jPanelBatch.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanelAction.add(jButtonCancel);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jPanelAction.add(jButtonOk);

        jComboBoxEventTypes = new javax.swing.JComboBox(this.eventTypes.asVector());
        jComboBoxEventTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEventTypesActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jComboBoxEventTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelAction, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanelBatch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboBoxEventTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelAction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelBatch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function is called when an event type is picked from the combo box.
     * It may be possible to pre-select a position in the text area and have
     * the event type inserted at that position using '.insert' or 
     * 'replaceSelection'.
     */
    private void jComboBoxEventTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEventTypesActionPerformed
        jTextAreaEpisodes.replaceSelection(jComboBoxEventTypes.getSelectedItem().toString() + '\n');
    }//GEN-LAST:event_jComboBoxEventTypesActionPerformed

    
    /**
     * Save the episode list in preferences
     */
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOkActionPerformed
    {//GEN-HEADEREND:event_jButtonOkActionPerformed
        update();
        // prefs.put("eventPositions", jTextAreaEpisodes.getText());
        
        cancelled = false;
        dialog.setVisible(false);
        dialog.dispose();        
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        cancelled = true;
        dialog.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxEventTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAction;
    private javax.swing.JPanel jPanelBatch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEpisodes;
    // End of variables declaration//GEN-END:variables
    
}
