/*
 * CustomProgressMonitor.java
 *
 * Created on November 9, 2006, 4:05 PM
 */

package edu.iisc.tdminer.gui;

import edu.iisc.tdminer.model.ThreadedProgressManager;
import java.awt.Frame;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JDialog;

/**
 *
 * @author  hzg3nc
 */
public class ProgressMonitorUI extends JDialog implements Runnable
{
    private int min = 0;
    private int max = 100;
    private int current = 0;
    private ThreadedProgressManager task;
    private Thread thread;
    
    private static ProgressMonitorUI instance;
    
    /** Creates new form CustomProgressMonitor */
    public ProgressMonitorUI(Frame frame, ThreadedProgressManager task)
    {
        super(frame, true);
        this.task = task;
        initComponents();
        jProgressBar1.setMinimum(min);
        jProgressBar1.setMaximum(max);
        jProgressBar1.setString("0%");
        jProgressBar1.setValue(0);
        if (frame != null)
        {
            int x = (int)(frame.getLocation().getX() + (frame.getSize().getWidth() - getSize().getWidth())/2);
            int y = (int)(frame.getLocation().getY() + (frame.getSize().getHeight() - getSize().getHeight())/2);
            setLocation(x,y);
        }            
    }
    
    public void startMonitorThread()
    {
        thread = new Thread(this);
        thread.start();
    }
    
    public void stopMonitorThread()
    {
        if (thread != null)
        {
            thread.interrupt();
            thread = null;
        }
    }

    public void setText(String text)
    {
        jLabel1.setText(text);
    }
    
    public void run()
    {
        System.out.println("Monitor started !!!");
        while(!Thread.interrupted())
        {
            try { Thread.sleep(500); } catch (InterruptedException ex){ break; }
            
            java.awt.EventQueue.invokeLater(new Runnable()
            {
                final private NumberFormat form = 
                        NumberFormat.getPercentInstance(Locale.US);
                public void run()
                {     
                    jLabel2.setText( form.format( task.getNetProgress() ) );
                    jProgressBar1.setValue( task.getProgress() );
                }
            });
        }
        System.out.println("Monitor ended !!!");
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Progress Indicator");
        setModal(true);
        setName("ProgressMonitor");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sample message");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" 0%");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 401, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(170, 170, 170)
                .add(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(4, 4, 4)
                .add(jButton1))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        stopMonitorThread();
        task.interrupt();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
