/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimeSeriesInput.java
 *
 * Created on Apr 28, 2010, 3:08:53 PM
 */

package edu.iisc.tdminer.gui;

import edu.iisc.tdminer.gui.reader.VisualCSVReader;
import edu.iisc.tdminer.util.Constants;
import edu.iisc.tdminercore.data.IEpisode;
import edu.iisc.tdminercore.data.Episode;
import edu.iisc.tdminercore.data.EventFactor;
import edu.iisc.tdminer.data.StateInfo;
import edu.iisc.tdminer.model.FreqEpisodeTableModel;
import edu.iisc.tdminercore.reader.IEventStreamReader;
import edu.iisc.tdminercore.data.IEventDataStream;
import edu.iisc.tdminercore.data.IEventDataStream.CONSTRAINT_MODE;
import edu.iisc.tdminercore.util.TimeConstraint;
import edu.iisc.tdminer.util.ColumnSorter;
import edu.iisc.tdminer.util.HistogramUtil;
import edu.iisc.tdminer.util.KMeans;

import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.NumberFormat;
import java.util.Collections;
import java.util.List;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ProgressMonitorInputStream;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import edu.iisc.tdminer.data.StateInfo;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author karl
 */
public class TimeSeriesInput extends javax.swing.JPanel implements ITaskPanel {
    private JLabel jLabelStatus;
    private JFrame frame;
    private StateInfo stateInfo;
    private JFileChooser fc;
    private FreqEpisodeTableModel model;
    private IEventDataStream sequence;
    private int start_col;
    private int end_col;


    /** Creates new form TimeSeriesInput */
    public TimeSeriesInput() {
        initComponents();
        fc = new JFileChooser();
        System.out.println("Time Series Input... init");
    }

    public void setJLabelStatus(JLabel jLabelStatus) {
        this.jLabelStatus = jLabelStatus;
    }

    public void setFrame(JFrame frame) {
        this.frame = frame;
    }

    public void setStateInfo(StateInfo stateInfo) {
        this.stateInfo = stateInfo;
    }

    public void loadData() {

    }

    boolean openDataSequence() {

        if (Constants.CURRENT_DIR != null)
        {
            fc.setCurrentDirectory(Constants.CURRENT_DIR);
        }
        int returnVal = fc.showOpenDialog(TimeSeriesInput.this);
        Constants.CURRENT_DIR = fc.getCurrentDirectory();

        if (returnVal != JFileChooser.APPROVE_OPTION)
        {
            System.out.println("Open command cancelled by user.");
            return false;
        }
        File file = fc.getSelectedFile();

        //This is where a real application would open the file.
        System.out.println("Opening: " + file.getName() + ".");
        jTextFieldFileName.setText(file.getPath());
        loadData();
        return true;
    }

     public void update()
     {
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFile = new javax.swing.JLabel();
        jTextFieldFileName = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("File Name"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        jLabelFile.setText("Time Series file name:");

        jTextFieldFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFileNameActionPerformed(evt);
            }
        });

        jButtonBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Open16.gif"))); // NOI18N
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBrowse))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButtonBrowse)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFileNameActionPerformed
        loadData();
}//GEN-LAST:event_jTextFieldFileNameActionPerformed

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        openDataSequence();
}//GEN-LAST:event_jButtonBrowseActionPerformed

    public void refreshState() {
        //update();
    }

    public void handleTaskCompletion(int taskIndex) {
        throw new UnsupportedOperationException("Not supported yet.");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFileName;
    // End of variables declaration//GEN-END:variables

}
